[project]
name = "latte-art-robot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10,<3.14"
dependencies = [
    "lerobot[pi] @ git+https://github.com/huggingface/lerobot.git",
    "wandb",
    "huggingface_hub",
    "accelerate",
]
